env:
  browser: true
  es2021: true
  node: true
extends:
  - react-app/jest
  - plugin:react/recommended
  - airbnb
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - import
rules:
  no-void:
    - error
    - allowAsStatement: true
  react/jsx-filename-extension:
    - error
    - extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react/react-in-jsx-scope: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-props-no-spreading: off
  react/require-default-props: off
  import/extensions: off
  import/prefer-default-export: off
  arrow-body-style: off
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/no-explicit-any':
    - warn
    - ignoreRestArgs: true
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/consistent-type-definitions':
    - error
    - 'type'
settings:
  import/resolver:
    typescript: {}
